---

- hosts: all
  become: true
  pre_tasks:

  - name: update and upgrade
    tags: always
    apt:
      upgrade: dist
      update_cache: yes


- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php
    tags: ubuntu,apache,apache2,php,20.11
    package:
      name: 
         - "{{ apache_package }}"
         - "{{ php_package }}"
      state: latest

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb
    tags: ubuntu,db,mariadb,20.9
    package:
      name: mariadb-server
      state: latest

  
 
