---

- hosts: all
  become: true
  pre_tasks:

  - name: update and upgrade
    tags: always
    apt:
      upgrade: dist
      update_cache: yes

- hosts: workstations
  become: true
  tasks:

  - name: install unzip
    tags: unzip,workstations
    package:
      name: unzip
      state: latest

  - name: extract and install terraform
    tags: extract,workstations,terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.8.4/terraform_1.8.4_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: true
      owner: root
      group: root
      mode: 0755


- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php
    tags: ubuntu,apache,apache2,php,20.11
    package:
      name: 
         - "{{ apache_package }}"
         - "{{ php_package }}"
      state: latest

  - name: copy default html file for site
    tags: ubuntu,html,apache,apache2,20.11
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb
    tags: ubuntu,db,mariadb,20.9
    package:
      name: mariadb-server
      state: latest

  
 
